import { EMEASURE_TYPE, Operation, TMeasureRoles, TVisualMeasureConfig } from "../models/VisualMeasure";

const visualMeasureConfig: TVisualMeasureConfig = {
    AC: [
        {
            id: 'PY',
            label: `PY`,
            operation: Operation.IND,
            formulaType: EMEASURE_TYPE.REF,
        },
        {
            id: 'PL',
            label: `[PL]`,
            operation: Operation.IND,
            formulaType: EMEASURE_TYPE.REF,
        },
        {
            id: 'FC',
            label: `[FC]`,
            operation: Operation.IND,
            formulaType: EMEASURE_TYPE.NULL,
        },
        {
            id: 'AC',
            label: `[AC]`,
            operation: Operation.IND,
            formulaType: EMEASURE_TYPE.ACTUAL,
        },
        {
            id: 'ΔPY',
            measureBasedLabel: `[AC] - [PY]`,
            label: 'ΔPY',
            operation: Operation.SUB,
            calcMeasures: ['AC', 'PY'],
            formulaType: EMEASURE_TYPE.ABSOLUTE_VARIANCE,
        },
        {
            id: 'ΔPY%',
            measureBasedLabel: `([AC] - [PY])%`,
            label: `ΔPY%`,
            operation: Operation.PCT,
            calcMeasures: ['AC', 'PY'],
            formulaType: EMEASURE_TYPE.RELATIVE_VARIANCE,
        },
        {
            id: 'ΔPL',
            measureBasedLabel: `[AC] - [PL]`,
            label: 'ΔPL',
            operation: Operation.SUB,
            calcMeasures: ['AC', 'PL'],
            formulaType: EMEASURE_TYPE.ABSOLUTE_VARIANCE,
        },
        {
            id: 'ΔPL%',
            measureBasedLabel: `([AC] - [PL])%`,
            label: 'ΔPL%',
            operation: Operation.PCT,
            calcMeasures: ['ΔPL', 'PL'],
            formulaType: EMEASURE_TYPE.RELATIVE_VARIANCE,
        },
        {
            id: 'ΔØ',
            measureBasedLabel: `[AC] - [Ø]`,
            label: 'ΔØ',
            operation: Operation.SUB,
            calcMeasures: ['AC', 'Ø'],
            formulaType: EMEASURE_TYPE.ABSOLUTE_VARIANCE,
        },
        {
            id: 'ΔØ%',
            measureBasedLabel: `([AC] - [Ø])%`,
            label: 'ΔØ%',
            operation: Operation.PCT,
            calcMeasures: ['ΔØ', 'Ø'],
            formulaType: EMEASURE_TYPE.RELATIVE_VARIANCE,
        },
    ],
    FC: [
        {
            id: 'PY',
            label: `PY`,
            operation: Operation.IND,
            formulaType: EMEASURE_TYPE.REF,
        },
        {
            id: 'PL',
            label: `[PL]`,
            operation: Operation.IND,
            formulaType: EMEASURE_TYPE.REF,
        },
        {
            id: 'FC',
            label: `[FC]`,
            operation: Operation.IND,
            formulaType: EMEASURE_TYPE.ACTUAL,
        },
        {
            id: 'ΔPL',
            measureBasedLabel: `[FC] - [PL]`,
            label: 'ΔPL',
            operation: Operation.SUB,
            calcMeasures: ['FC', 'PL'],
            formulaType: EMEASURE_TYPE.ABSOLUTE_VARIANCE,
        },
        {
            id: 'ΔPL%',
            measureBasedLabel: `([FC] - [PL])%`,
            label: 'ΔPL%',
            operation: Operation.PCT,
            calcMeasures: ['FC', 'PL'],
            formulaType: EMEASURE_TYPE.RELATIVE_VARIANCE,
        },
        {
            id: 'ΔPY',
            measureBasedLabel: `[FC] - [PY]`,
            label: 'ΔPY',
            operation: Operation.SUB,
            calcMeasures: ['FC', 'PY'],
            formulaType: EMEASURE_TYPE.ABSOLUTE_VARIANCE,
        },
        {
            id: 'ΔPY%',
            measureBasedLabel: `([FC] - [PY])%`,
            label: 'ΔPY%',
            operation: Operation.PCT,
            calcMeasures: ['FC', 'PY'],
            formulaType: EMEASURE_TYPE.RELATIVE_VARIANCE,
        },
        {
            id: 'ΔØ',
            measureBasedLabel: `[FC] - [Ø]`,
            label: 'ΔØ',
            operation: Operation.SUB,
            calcMeasures: ['FC', 'Ø'],
            formulaType: EMEASURE_TYPE.ABSOLUTE_VARIANCE,
        },
        {
            id: 'ΔØ%',
            measureBasedLabel: `([FC] - [Ø])%`,
            label: 'ΔØ%',
            operation: Operation.PCT,
            calcMeasures: ['ΔØ', 'Ø'],
            formulaType: EMEASURE_TYPE.RELATIVE_VARIANCE,
        },
    ],
    PY: [
        {
            id: 'PY',
            label: `[PY]`,
            operation: Operation.IND,
            formulaType: EMEASURE_TYPE.ACTUAL,
        },
        {
            id: 'PL',
            label: `[PL]`,
            operation: Operation.IND,
            formulaType: EMEASURE_TYPE.REF,
        },
        {
            id: 'ΔPL',
            measureBasedLabel: `[PY] - [PL]`,
            label: 'ΔPL',
            operation: Operation.SUB,
            calcMeasures: ['PY', 'PL'],
            formulaType: EMEASURE_TYPE.ABSOLUTE_VARIANCE,
        },
        {
            id: 'ΔPL%',
            measureBasedLabel: `([PY] - [PL])%`,
            label: 'ΔPL%',
            operation: Operation.PCT,
            calcMeasures: ['PY', 'PL'],
            formulaType: EMEASURE_TYPE.RELATIVE_VARIANCE,
        },
        {
            id: 'ΔØ',
            measureBasedLabel: `[PY] - [Ø]`,
            label: 'ΔØ',
            operation: Operation.SUB,
            calcMeasures: ['PY', 'Ø'],
            formulaType: EMEASURE_TYPE.ABSOLUTE_VARIANCE,
        },
        {
            id: 'ΔØ%',
            measureBasedLabel: `([PY] - [Ø])%`,
            label: 'ΔØ%',
            operation: Operation.PCT,
            calcMeasures: ['ΔØ', 'Ø'],
            formulaType: EMEASURE_TYPE.RELATIVE_VARIANCE,
        },
    ],
    PL: [
        {
            id: 'PL',
            label: `[PL]`,
            operation: Operation.IND,
            formulaType: EMEASURE_TYPE.ACTUAL,
        },
        {
            id: 'ΔØ',
            measureBasedLabel: `[PL] - [Ø]`,
            label: 'ΔØ',
            operation: Operation.SUB,
            calcMeasures: ['PL', 'Ø'],
            formulaType: EMEASURE_TYPE.ABSOLUTE_VARIANCE,
        },
        {
            id: 'ΔØ%',
            measureBasedLabel: `([PL] - [Ø])%`,
            label: 'ΔØ%',
            operation: Operation.PCT,
            calcMeasures: ['ΔØ', 'Ø'],
            formulaType: EMEASURE_TYPE.RELATIVE_VARIANCE,
        },
    ],
};

export const getVisualMeasureConfig = (measureKey: TMeasureRoles) => {
    return visualMeasureConfig[measureKey];
};